<?php global $zym_decrypt;$zym_decrypt['ÁÖ®ÖÀýÃÃÃ®ˆŽ¾ˆÖ¯ÃÃ¾¯ˆÄ®¥ÃýÖ¥Ž”ýÄ']=base64_decode('ZGVmaW5lZA==');$zym_decrypt['Ž¯¯”‹¯¯¾®¥Ã”®ÄýÁ¥¯”Ãˆ¥ŽÃ‹Ž”®¯¾ˆ®']=base64_decode('aGVhZGVy');$zym_decrypt['ýÄÀÁ”ÁÀÀŽÄ‹¥À‹®Ö®ÁÀý‹”ˆ¾ÁŽÀ®ÄÄÃˆ']=base64_decode('ZGFkZHNsYXNoZXM=');$zym_decrypt['Ä‹ýÖ¯‹®Ã”ÃÖ®‹ÀÖÖÀÀ”ÃÁÖ¥”Ã®‹ÄÃÁÄÖ']=base64_decode('bWQ1');$zym_decrypt['¯ˆÖýÃ®À¥¯ÖÁÖˆ‹¥ÖÃ®¥Ã¥ýÄÖÁÖÁÖ‹¯®Ã']=base64_decode('dHJpbQ==');$zym_decrypt['”¯ŽÁÁŽÖ¥”ýŽÃˆ”¯ŽÄ”ˆ¯ýÃÄÖ”ˆ¾ÖÖÀÀ¥']=base64_decode('c3RydG9sb3dlcg=='); ?>
<?php
if(!$GLOBALS['zym_decrypt']['ÁÖ®ÖÀýÃÃÃ®ˆŽ¾ˆÖ¯ÃÃ¾¯ˆÄ®¥ÃýÖ¥Ž”ýÄ'](base64_decode('SU5fQ1JPTkxJVEU=')))exit();@$GLOBALS['zym_decrypt']['Ž¯¯”‹¯¯¾®¥Ã”®ÄýÁ¥¯”Ãˆ¥ŽÃ‹Ž”®¯¾ˆ®'](base64_decode('Q29udGVudC1UeXBlOiB0ZXh0L2h0bWw7IGNoYXJzZXQ9VVRGLTg='));if($islogin==1){$type=isset($_GET['type'])?$GLOBALS['zym_decrypt']['ýÄÀÁ”ÁÀÀŽÄ‹¥À‹®Ö®ÁÀý‹”ˆ¾ÁŽÀ®ÄÄÃˆ']($_GET['type']):exit('No type!');$orderid=isset($_GET['orderid'])?$GLOBALS['zym_decrypt']['ýÄÀÁ”ÁÀÀŽÄ‹¥À‹®Ö®ÁÀý‹”ˆ¾ÁŽÀ®ÄÄÃˆ']($_GET['orderid']):exit('No orderid!');$row=$DB->get_row("SELECT * FROM ".DBQZ."_pay WHERE orderid='{$orderid}' limit 1");if(!$row['id'])exit('è¯¥è®¢å•å·ä¸å­˜åœ¨ï¼Œè¯·è¿”å›žæ¥æºåœ°é‡æ–°å‘èµ·è¯·æ±‚ï¼');if($type=='tenpay2'){$data =$conf['tenpay_account'] . '&' .$row['money']. '&' . $orderid;echo base64_decode('PGZvcm0gYWN0aW9uPSJodHRwczovL3d3dy50ZW5wYXkuY29tL3YyL2FjY291bnQvcGF5L3BheW1vcmVfY2Z0LnNodG1sIiBtZXRob2Q9ImdldCIgbmFtZT0idGVucGF5Ij4NCgkJCTxpbnB1dCB0eXBlPSJoaWRkZW4iIG5hbWU9ImRhdGEiIHZhbHVlPSI=').$data.'" />
			<input type="hidden" name="validate" value="'.$GLOBALS['zym_decrypt']['Ä‹ýÖ¯‹®Ã”ÃÖ®‹ÀÖÖÀÀ”ÃÁÖ¥”Ã®‹ÄÃÁÄÖ']($data).'" /></form><script>document.tenpay.submit();</script>';}elseif($type=='alipay'){require_once(SYSTEM_ROOT."alipay/alipay.config.php");require_once(SYSTEM_ROOT.base64_decode('YWxpcGF5L2FsaXBheV9zdWJtaXQuY2xhc3MucGhw'));if($ismobile==true && $conf['alipay2_api']==1){$parameter =array("service" => "alipay.wap.create.direct.pay.by.user", "partner" => $GLOBALS['zym_decrypt']['¯ˆÖýÃ®À¥¯ÖÁÖˆ‹¥ÖÃ®¥Ã¥ýÄÖÁÖÁÖ‹¯®Ã']($conf['alipay_pid']), "seller_id" => $GLOBALS['zym_decrypt']['¯ˆÖýÃ®À¥¯ÖÁÖˆ‹¥ÖÃ®¥Ã¥ýÄÖÁÖÁÖ‹¯®Ã']($conf['alipay_account']), "payment_type" => "1", "notify_url" => $siteurl.'other/alipay_notify.php', "return_url" => $siteurl.'other/alipay_return.php', "out_trade_no" => $orderid, "subject" => $row['name'], "total_fee" => $row['money'], "_input_charset" => $GLOBALS['zym_decrypt']['”¯ŽÁÁŽÖ¥”ýŽÃˆ”¯ŽÄ”ˆ¯ýÃÄÖ”ˆ¾ÖÖÀÀ¥']('utf-8'));}else{$parameter =array("service" => "create_direct_pay_by_user", "partner" => $GLOBALS['zym_decrypt']['¯ˆÖýÃ®À¥¯ÖÁÖˆ‹¥ÖÃ®¥Ã¥ýÄÖÁÖÁÖ‹¯®Ã']($conf['alipay_pid']), "seller_email" => $GLOBALS['zym_decrypt']['¯ˆÖýÃ®À¥¯ÖÁÖˆ‹¥ÖÃ®¥Ã¥ýÄÖÁÖÁÖ‹¯®Ã']($conf['alipay_account']), "payment_type" => "1", "notify_url" => $siteurl.'other/alipay_notify.php', "return_url" => $siteurl.'other/alipay_return.php', "out_trade_no" => $orderid, "subject" => $row['name'], "total_fee" => $row['money'], "_input_charset" => $GLOBALS['zym_decrypt']['”¯ŽÁÁŽÖ¥”ýŽÃˆ”¯ŽÄ”ˆ¯ýÃÄÖ”ˆ¾ÖÖÀÀ¥']('utf-8'));}$alipaySubmit =new AlipaySubmit($alipay_config);$html_text =$alipaySubmit->buildRequestForm($parameter,"get", "æ­£åœ¨è·³è½¬");echo $html_text;}elseif($type=='tenpay'){require_once(SYSTEM_ROOT."tenpay/RequestHandler.class.php");$reqHandler =new RequestHandler();$reqHandler->init();$reqHandler->setKey($conf['tenpay_key']);$reqHandler->setGateUrl("https://gw.tenpay.com/gateway/pay.htm");$reqHandler->setParameter("partner", trim($conf['tenpay_pid']));$reqHandler->setParameter("out_trade_no", $orderid);$reqHandler->setParameter("total_fee", $row['money']*100);$reqHandler->setParameter("return_url", $siteurl.'other/tenpay_return.php');$reqHandler->setParameter("notify_url", $siteurl.'other/tenpay_notify.php');$reqHandler->setParameter("body", $row['name']);$reqHandler->setParameter("bank_type", "DEFAULT");$reqHandler->setParameter("spbill_create_ip", $clientip);$reqHandler->setParameter("fee_type", "1");$reqHandler->setParameter("subject",$row['name']);$reqHandler->setParameter("sign_type", "MD5");$reqHandler->setParameter("service_version", "1.0");$reqHandler->setParameter("input_charset", "utf-8");$reqHandler->setParameter("sign_key_index", "1");$reqUrl =$reqHandler->getRequestURL();?>
		<form action="<?php echo $reqHandler->getGateUrl()?>" method="post" id="tenpay">
		<?php
 $params =$reqHandler->getAllParameters();foreach($params as $k => $v){echo "<input type=\"hidden\" name=\"{$k}\" value=\"{$v}\" />\n";}?>
		<input type="submit" value="æ­£åœ¨è·³è½¬"></form><script>document.getElementById("tenpay").submit();</script>
		<?php
 }elseif($type=='wxpay'){}}else{exit('ç™»å½•å¤±è´¥ï¼Œå¯èƒ½æ˜¯å¯†ç é”™è¯¯æˆ–è€…èº«ä»½å¤±æ•ˆäº†ï¼Œè¯·é‡æ–°ç™»å½•ï¼');}