<?php global $zym_decrypt;$zym_decrypt['ÁÖ®ÖÀıÃÃÃ®ˆ¾ˆÖ¯ÃÃ¾¯ˆÄ®¥ÃıÖ¥”ıÄ']=base64_decode('ZGVmaW5lZA==');$zym_decrypt['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®']=base64_decode('c2F2ZVNldHRpbmc=');$zym_decrypt['ÁÃÃ”®ÖˆÄÁÀÃÀı¾ıˆ¥ÀÖˆı‹”ÁÖÖıÀ¾¯']=base64_decode('cmFuZG9t');$zym_decrypt['Ãı®ÃÄˆÖıˆ‹À¾ÄÖÀÄ¥Öı¯ÀÃÖ¾”¾Ã¾”']=base64_decode('ZmlsZV9nZXRfY29udGVudHM=');$zym_decrypt['Áı®‹Á¾¯ÖÃÀÄÖÃ®ÖÃÃ®¾À¾Ã¾ÃÃÁˆ¾®Ã¥Ã']=base64_decode('c3RyX3JlcGxhY2U=');$zym_decrypt['”ÖÖÄ‹¾Ä¾¯ÃÖ¾ÖÁÖÃÀ‹ÀÃ”¾Ã®Ö””ˆÖÄ']=base64_decode('ZXhwbG9kZQ==');$zym_decrypt['ˆÖ¯¥ÖÀ¥ÁÖˆÖÖ®‹ÖÄ¾ˆ‹Ö‹ÃÃ®ı”¾®¾®']=base64_decode('Y291bnQ=');$zym_decrypt['¥ÄˆÃ”Ã®Ãˆ®ıÁ‹¾¯”Á¯Á®¥Ö”ı¾Ö¥ÁÖÖ¾Ö']=base64_decode('ZmlsZV9leGlzdHM=');$zym_decrypt['ÃÖıˆÖ®ıÃÖÃ¥ÃÖÁ¯ˆÄÖÁˆÃÄıÁ¾Á”À‹ı‹ˆ']=base64_decode('ZmlsZV9wdXRfY29udGVudHM='); ?>
<?php
include(base64_decode('dXBkYXRlLmluYy5waHA='));$do=isset($_GET['do'])?$_GET['do']:1;?>
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<meta name="viewport" content="width=device-width; initial-scale=1.0;  minimum-scale=1.0; maximum-scale=2.0"/>
<link rel="stylesheet" type="text/css" href="../style/css1.css">
<link rel="shortcut icon" href="../images/favicon.ico">
<title>æ›´æ–°ç¨‹åºV6</title>
</head>
<body style="max-width:480px;">
<?php
 if($conf['version']=='6500'){echo '<div class="w h">ç³»ç»Ÿæç¤º:</div><div class="box">æ‚¨å·²ç»å‡çº§åˆ°V6.17ç‰ˆæœ¬!</div>';}else {if($GLOBALS['zym_decrypt']['ÁÖ®ÖÀıÃÃÃ®ˆ¾ˆÖ¯ÃÃ¾¯ˆÄ®¥ÃıÖ¥”ıÄ'](base64_decode('U1FMSVRF'))){exit(base64_decode('U1FMaXRl5pWw5o2u5bqT5LiN5pSv5oyB5pu05paw77yB6K+35L2/55So5YWo5paw5a6J6KOF44CC'));}if(!$conf['version'] || $conf['version']<'5040'){exit('<div class="w h">ç³»ç»Ÿæç¤º:</div><div class="box">è¯· <a href="update2.php">ç‚¹å‡»æ­¤å¤„</a> å®Œæˆå‡çº§ã€‚</div>');}if($conf['version']=='6240'){$sql="ALTER TABLE  `".DBQZ."_qq` ADD  `superkey` VARCHAR(150) NULL,
 ADD  `supertoken` VARCHAR(150) NULL,
 ADD  `qqlevel` VARCHAR(80) NULL";$sql2="ALTER TABLE  `".DBQZ."_user` ADD  `peie` int(11) default 5,
 ADD  `invite` VARCHAR(150) NULL";$sql3="REPLACE INTO `".DBQZ."_config` (`k`, `v`) VALUES
('sleep', '0'),
('peie_open', '0'),
('peie_free', '5'),
('coin_topeie', '500'),
('qqloginid', '1'),
('mzjc_api', '0'),
('newpc', '0')";echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');if($DB->query($sql)&& $DB->query($sql2)&& $DB->query($sql3)){saveSetting('version','6500');echo base64_decode('djYuMTfmlbDmja7lupPmm7TmlrDmiJDlip/vvIE8YnI+PGJyPjxhIGhyZWY9Ii4uL2luZGV4LnBocCI+Pj7ov5Tlm57nvZHnq5npppbpobU8L2E+');}else{$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('dmVyc2lvbg=='),base64_decode('NjUwMA=='));exit(base64_decode('5L2g5bey5pu05paw6L+H77yBPGJyLz4=').$DB->error().'<br><a href="../index.php">>>è¿”å›ç½‘ç«™é¦–é¡µ</a>');}}elseif($conf['version']=='6150'){$sql="ALTER TABLE  `".DBQZ."_qq` ADD  `ptsig` VARCHAR(150) NULL,
 ADD  `pskey` VARCHAR(150) NULL,
 ADD  `pskey2` VARCHAR(150) NULL";echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');if($DB->query($sql)){saveSetting('version','6240');echo base64_decode('djYuMTTmlbDmja7lupPmm7TmlrDmiJDlip/vvIE8YnI+PGJyPjxhIGhyZWY9Ij8iPj4+54K55q2k57un57utPC9hPg==');}else{$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('dmVyc2lvbg=='),base64_decode('NjI0MA=='));exit(base64_decode('5L2g5bey5pu05paw6L+H77yBPGJyLz4=').$DB->error().'<br><a href="?">>>ç‚¹æ­¤ç»§ç»­</a>');}}elseif($conf['version']=='6140'){$sql="ALTER TABLE `".DBQZ."_user`
ADD `mail_on` int(1) NOT NULL DEFAULT '1',
ADD `vipsign` int(11) NOT NULL DEFAULT 0,
ADD `vipjf` int(11) NOT NULL DEFAULT 0,
ADD `vipsigntime` date NULL";$sql2="ALTER TABLE  `".DBQZ."_job` MODIFY COLUMN `url` text NOT NULL";echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');if($DB->query($sql)&& $DB->query($sql2)){saveSetting('version','6150');echo base64_decode('djYuNeaVsOaNruW6k+abtOaWsOaIkOWKn++8gTxicj48YnI+PGEgaHJlZj0iPyI+Pj7ngrnmraTnu6fnu608L2E+');}else{$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('dmVyc2lvbg=='),base64_decode('NjE1MA=='));exit(base64_decode('5L2g5bey5pu05paw6L+H77yBPGJyLz4=').$DB->error().'<br><a href="?">>>ç‚¹æ­¤ç»§ç»­</a>');}}elseif($conf['version']=='6000'){$sql="ALTER TABLE `".DBQZ."_user`
ADD `daili` int(1) NOT NULL DEFAULT '0',
ADD `daili_rmb` VARCHAR(100) NOT NULL DEFAULT '0',
ADD `daili_qq` VARCHAR(20) NOT NULL DEFAULT '0'";$sql2="ALTER TABLE `".DBQZ."_kms`
ADD `daili` int(11) NOT NULL DEFAULT '0'";echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');if($DB->query($sql)&& $DB->query($sql2)){saveSetting('version','6140');echo base64_decode('djYuNOaVsOaNruW6k+abtOaWsOaIkOWKn++8gTxicj48YnI+PGEgaHJlZj0iPyI+Pj7ngrnmraTnu6fnu608L2E+');}else{$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('dmVyc2lvbg=='),base64_decode('NjE0MA=='));exit(base64_decode('5L2g5bey5pu05paw6L+H77yBPGJyLz4=').$DB->error().'<br><a href="?">>>ç‚¹æ­¤ç»§ç»­</a>');}}elseif($conf['version']<'6000'){echo '<div class="w h">V6.0æ›´æ–°ç¨‹åº</div>';if($do=='1'){$_SESSION['updatestep']=1;$DB->query("update `".DBQZ."_config` `switch` ='0' where `id`='1';");echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');echo base64_decode('PHByZT4=');include(base64_decode('Li4vcmVhZG1lLnR4dA=='));echo base64_decode('PC9wcmU+');echo "<hr><a href='{$_SERVER['PHP_SELF']}?do=2'>>>ç«‹å³å¼€å§‹æ›´æ–°</a>";}elseif($do=='2'){if($_SESSION['updatestep']<=1){$c=0;$row=$DB->get_row("SELECT * FROM ".DBQZ."_config where id='1' limit 1");$DB->query("DROP TABLE IF EXISTS ".DBQZ."_config");$DB->query("create table `".DBQZ."_config` (
`k` varchar(32) NOT NULL,
`v` text NULL,
PRIMARY KEY  (`k`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");foreach($row as $k => $v){if($k=='id')continue;$sql="insert into ".DBQZ."_config (`k`,`v`) values ('$k','$v')";$DB->query($sql);$c++;}$_SESSION['updatestep']=2;}echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij7mlbDmja7ooajovazmjaLmiJDlip/vvIjkuIDvvIk8YnIvPlNRTOWFseaJp+ihjA==').$c.'å¥<br/><a href="'.$_SERVER['PHP_SELF'].'?do=3">>>ä¸‹ä¸€æ­¥</a>';}elseif($do=='3'){if($_SESSION['updatestep']<=2){$c=0;$syskey =$GLOBALS['zym_decrypt']['ÁÃÃ”®ÖˆÄÁÀÃÀı¾ıˆ¥ÀÖˆı‹”ÁÖÖıÀ¾¯'](32);$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('c3lza2V5'),$syskey);$rs=$DB->query("SELECT * FROM ".DBQZ."_qq order by id asc");while($row =$DB->fetch($rs)){$qq=$row['qq'];$pw=authcode($row['pw'],'ENCODE',$syskey);$sql="update ".DBQZ."_qq set pw='{$pw}' where qq='".$qq."'";$DB->query($sql);$c++;}$_SESSION['updatestep']=3;}echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij7mlbDmja7ooajovazmjaLmiJDlip/vvIjkuozvvIk8YnIvPlNRTOWFseaJp+ihjA==').$c.'å¥<br/><a href="'.$_SERVER['PHP_SELF'].'?do=4">>>ä¸‹ä¸€æ­¥</a>';}elseif($do=='4'){if($_SESSION['updatestep']<=3){$c=0;$d=0;$a=$GLOBALS['zym_decrypt']['Ãı®ÃÄˆÖıˆ‹À¾ÄÖÀÄ¥Öı¯ÀÃÖ¾”¾Ã¾”']("update3.sql");$a=$GLOBALS['zym_decrypt']['Áı®‹Á¾¯ÖÃÀÄÖÃ®ÖÃÃ®¾À¾Ã¾ÃÃÁˆ¾®Ã¥Ã']('{DBQZ}', DBQZ, $a);$a=$GLOBALS['zym_decrypt']['”ÖÖÄ‹¾Ä¾¯ÃÖ¾ÖÁÖÃÀ‹ÀÃ”¾Ã®Ö””ˆÖÄ'](";",$a);$error='';for($i=0;$i<$GLOBALS['zym_decrypt']['ˆÖ¯¥ÖÀ¥ÁÖˆÖÖ®‹ÖÄ¾ˆ‹Ö‹ÃÃ®ı”¾®¾®']($a);$i++){if($DB->query($a[$i])){$c++;}else{$d++;$error.=$DB->error().'<br/>';}}$_SESSION['updatestep']=4;}echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij4=');echo base64_decode('5pWw5o2u6KGo57uT5p6E5pu05paw5oiQ5YqfPGJyLz5TUUzmiJDlip8=').$c.'å¥/å¤±è´¥'.$d.'å¥<br/><a href="'.$_SERVER['PHP_SELF'].'?do=5">>>ä¸‹ä¸€æ­¥</a>';}elseif($do=='5'){$_SESSION['updatestep']=5;$u="http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];if(!$GLOBALS['zym_decrypt']['¥ÄˆÃ”Ã®Ãˆ®ıÁ‹¾¯”Á¯Á®¥Ö”ı¾Ö¥ÁÖÖ¾Ö'](base64_decode('aW5zdGFsbC5sb2Nr')))@$GLOBALS['zym_decrypt']['ÃÖıˆÖ®ıÃÖÃ¥ÃÖÁ¯ˆÄÖÁˆÃÄıÁ¾Á”À‹ı‹ˆ'](base64_decode('aW5zdGFsbC5sb2Nr'),base64_decode('d29uZQ=='));@$GLOBALS['zym_decrypt']['Ãı®ÃÄˆÖıˆ‹À¾ÄÖÀÄ¥Öı¯ÀÃÖ¾”¾Ã¾”']("http://www.qqzzz.net/api/tongji3.php?url=$u");$GLOBALS['zym_decrypt']['®®Ã®®”®ˆ¾ÖÀÀÃıÀı¯ˆ¥ˆˆˆ¯®‹ÃÃ®'](base64_decode('dmVyc2lvbg=='),base64_decode('NjAwMA=='));$CACHE->clear();echo base64_decode('PGRpdiBjbGFzcz0iYm94Ij48Zm9udCBjb2xvcj0iZ3JlZW4iPuabtOaWsOaIkOWKn++8geW9k+WJjeeJiOacrCBWNi4wPC9mb250Pjxici8+PGJyLz48YSBocmVmPSI/Ij4+PueCueatpOe7p+e7rTwvYT4=');}}}echo base64_decode('PGhyPg==');include(ROOT.base64_decode('aW5jbHVkZXMvZm9vdC5waHA='));echo base64_decode('PC9kaXY+PC9ib2R5PjwvaHRtbD4=');?>